### PR TITLE
 added translation table and fixed a few things

### PR DESCRIPTION
**Pull request by pletzer**
Some improvements but would still need someone to proofread the text and check the commands.

### CODE REVIEW

**Comment by chrisdjscott** [comment]
@pletzer it might be worth having full source code for your simple example. You already have the C file but maybe a setup.py and python script that shows everything together - what do you think? Then people can copy and paste the files and run it themselves easily.

**Comment by pletzer** [comment]
Thanks @chrisdjscott. I added a link to a setup.py file and wrote the ctypes interface in ready-to-copy form.

**Comment by chrisdjscott** [comment]
@pletzer did you push? I can only see the one original commit in here...

**Comment by pletzer** [comment]
@chrisdjscott, Sorry done.

**Pull request merged**
