### PR TITLE
MPI code example

### PR DESCRIPTION
**Pull request by tinyendian**
Here is a first cut of an MPI code example. The description of the individual steps can probably be improved.

Note that I am using NumPy's `array_split` method to divide up work between MPI ranks - this is a very robust way to distribute work as evenly as possible between ranks, and will always result in a usable split, even when running the code with a nonsensical number of MPI ranks. If you like it, it could be implemented in the solution as well - unless mpi4py has some built-in way to do that.

### CODE REVIEW

**Review by pletzer — COMMENTED** [review]
Hi @tinyendian, thanks for adding the example code. Below are some comments, I will let @chrisdjscott and @mand35 decide whether they are appropriate.

* Can we we add a space "nprocs-1" -> "nproc - 1"?
* Can we add space after comma: "numpy.array_split(numpy.arange(array.size),nprocs)" -> "numpy.array_split(numpy.arange(array.size), nprocs)"?
* Some comments would be good
* Should we define "array" just before filling in the elements, before line 71?
* If we define "array" as a flat array then we won't need to use "flat"
* Should we have a line "Save the above in file named ex.py; to execute ex.py using 7 processes type `srun --ntasks=7 python ex.py` (adding other srun options such as --account as required). We can then remove the section ## Running the scatter code using multiple MPI processes.

**Comment by pletzer** [comment]
I like the array_split call...

**Comment by pletzer** [comment]
Can we also replace the loop 
for index in pe_indices:
 ...
with vectorised statement?

**Comment by mand35** [comment]
I agree with @pletzer in the mentioned points above. Adding spaces and comments for a better reading. Furthermore, since we want to concentrate on MPI I would use as less as possible additional functionalities. Keep it simple. From that point of view. I would get rid of the "flat" function and initialize the array.  Additional, please describe in words what the algorithm is doing (as comment), thus the reader can verify that he is understanding the code correctly.

**Comment by pletzer** [comment]
this had been superseded by #46

**Pull request closed without merging**
