### PR TITLE
OMP docu first draft + typo correction

### PR DESCRIPTION
**Pull request by mand35**

### CODE REVIEW

**Review by pletzer — CHANGES_REQUESTED** [review]
Hi @mand35. 

Thanks for writing the doc. Looks good. Following are some suggestions for improvement. Let me know what you think. Feel free to accept/reject the suggestions. Modify the text in your branch if you accept the suggestion - no need to create a new pull request. Let me know when you're done.

1. "This approach we used while porting our python code to C++. This reduced the numerical overhead." to "This approach was used while porting Python code to C++ by removing the interpreter's overhead."

2. "Another way of improving the performance is using more resources to compute our tasks. Most of modern computers have multi-core CPUs. Each of these cores can compute instructions. All of them can access the shared memory." to "Another way of improving performance is by using more resources. Most of modern computers have multi-core CPUs. Each of these cores can in principle compute instructions in parallel. All cores can access the same, shared memory so we will need to be careful about instructions stepping over each other (race condition)." 

3. "can be implemented by pragmas and API  (see below)" to "can be implemented by pragmas and API (see below)". Just remove the extra space.

4. "instruct the compiler to apply OMP threading" to "instruct the compiler to apply OpenMP threading". Let's avoid using acronyms.

5. "OpenMP parallelisation is applied by the compiler, controlled using following compiler switched:" to "OpenMP parallelisation is applied by the compiler and is controlled by the following compiler switches:"

6. "Cray: enabled by default" to "Cray: OpenMP is enabled by default"

7. "These are followed by the _directive name_ and _clauses_" to "These are followed by the _directive names_ and _clauses_"

8. What is the line continuation symbol? In C and Fortran?. Line 62

9. "The most common procedure is parallelizing a loop to a bunch of threads." to "The most common procedure is parallelising a loop. " We use GB spelling conventions.

10. "The application always starts as serial, the so called Master Thread." to "The application always starts in serial". (Maybe no need to mention the master thread...?)

11. "With the `parallel` statment we spawn threads."  to "With the `parallel` statement we spawn threads. The number of threads is set by the environment variable `OMP_NUM_THREADS`, which can be set to anything from 1 to the number of cores on a nodes, e.g. `export OMP_NUM_THREADS=36`. "

12. "The arrays `x` and `y` are shared, thus all threads act (here only read) on the same memory" to "Arrays `x` and `y` are shared - each thread have access to the same arrays `x` and `y`". No need to use the article "the" for specific things...

13. "The data clause of the array `arr` needs to be defined as `private` thus each thread gets its own copy and race conditions are prevented." to "Array `arr` is declared as `private` with each thread getting its own copy to prevent race conditions."

14. "Furthermore, the values of `res` is meant to sum values of all iterations. Therefore, it needs to be collected from all threads. This operation is instructed using the `reduction(+:res)` directive, specifying the operation and the variables." to "The sum across iterations is stored in `res`, the value of which must be collected from all thread. This is indicated by the `reduction(+:res)` directive."

**Comment by pletzer** [comment]
We'll need to provide an exercise for the student at some point. At least have a place holder for the exercise. 

A possibility would be to have the student add the OMP directives and measure the speedup. Given that the non-openmp version of the code runs in a few seconds, we will likely need to increase the size of the problem. Since it is the loops over the obstacle segments that are parallelised, should run scatter.py -nc 512, 1024 or more to see good scaling. In addition, may want to increase the grid resolution (-nx 256 -ny 256) to slow down the code a bit.

**Comment by mand35** [comment]
What you mean with Nr.7?

**Comment by mand35** [comment]
I corrected the suggested changes.

**Review by pletzer — APPROVED** [review]

**Comment by pletzer** [comment]
Thanks @mand35, I merged.

**Pull request closed without merging**
