### PR TITLE
Change position of the working dir description

### PR DESCRIPTION
**Pull request by mand35**

### CODE REVIEW

**Comment by chrisdjscott** [comment]
@mand35 there are conflicts in a couple of the lessons - can you fix?

**Comment by mand35** [comment]
merged

**Review by pletzer — COMMENTED** [review]
We should have a discussion about where the "cd statement" should be typed. At the beginning or the end?

**Comment by pletzer** [comment]
I'm closing this pull-request as we have not been able to resolve where the cd command should be. There are pros and cons... In any case the material changed so much that it would be difficult to merge.

**Pull request closed without merging**
